// Licensed to Alexandre VILAIN under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Alexandre VILAIN licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tanstackai

import (
	"context"

	"github.com/alexandrevilain/tanstack-ai-go/provider"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvent creates a new instance of MockEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvent {
	mock := &MockEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvent is an autogenerated mock type for the Event type
type MockEvent struct {
	mock.Mock
}

type MockEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvent) EXPECT() *MockEvent_Expecter {
	return &MockEvent_Expecter{mock: &_m.Mock}
}

// EventType provides a mock function for the type MockEvent
func (_mock *MockEvent) EventType() EventType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventType")
	}

	var r0 EventType
	if returnFunc, ok := ret.Get(0).(func() EventType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(EventType)
	}
	return r0
}

// MockEvent_EventType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventType'
type MockEvent_EventType_Call struct {
	*mock.Call
}

// EventType is a helper method to define mock.On call
func (_e *MockEvent_Expecter) EventType() *MockEvent_EventType_Call {
	return &MockEvent_EventType_Call{Call: _e.mock.On("EventType")}
}

func (_c *MockEvent_EventType_Call) Run(run func()) *MockEvent_EventType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvent_EventType_Call) Return(eventType EventType) *MockEvent_EventType_Call {
	_c.Call.Return(eventType)
	return _c
}

func (_c *MockEvent_EventType_Call) RunAndReturn(run func() EventType) *MockEvent_EventType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// ChatStream provides a mock function for the type MockProvider
func (_mock *MockProvider) ChatStream(ctx context.Context, messages []Message, tools []Tool, model string, sink provider.EventSink) error {
	ret := _mock.Called(ctx, messages, tools, model, sink)

	if len(ret) == 0 {
		panic("no return value specified for ChatStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []Message, []Tool, string, provider.EventSink) error); ok {
		r0 = returnFunc(ctx, messages, tools, model, sink)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_ChatStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatStream'
type MockProvider_ChatStream_Call struct {
	*mock.Call
}

// ChatStream is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []Message
//   - tools []Tool
//   - model string
//   - sink provider.EventSink
func (_e *MockProvider_Expecter) ChatStream(ctx interface{}, messages interface{}, tools interface{}, model interface{}, sink interface{}) *MockProvider_ChatStream_Call {
	return &MockProvider_ChatStream_Call{Call: _e.mock.On("ChatStream", ctx, messages, tools, model, sink)}
}

func (_c *MockProvider_ChatStream_Call) Run(run func(ctx context.Context, messages []Message, tools []Tool, model string, sink provider.EventSink)) *MockProvider_ChatStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []Message
		if args[1] != nil {
			arg1 = args[1].([]Message)
		}
		var arg2 []Tool
		if args[2] != nil {
			arg2 = args[2].([]Tool)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 provider.EventSink
		if args[4] != nil {
			arg4 = args[4].(provider.EventSink)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProvider_ChatStream_Call) Return(err error) *MockProvider_ChatStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_ChatStream_Call) RunAndReturn(run func(ctx context.Context, messages []Message, tools []Tool, model string, sink provider.EventSink) error) *MockProvider_ChatStream_Call {
	_c.Call.Return(run)
	return _c
}
